In [78]:
import matplotlib as plt
import pandas as pd
import numpy as np
from math import sqrt
from statistics import mean
from numpy import array
import numpy as np

In [79]:
merge_table = pd.read_csv('merge_table_test')

In [80]:
merge_table["SIU_CUST_YN"] = None

In [81]:
merge_table['AGE'].fillna((merge_table['AGE'].mean()), inplace=True)

merge_table['AGE'] = merge_table['AGE'].map(lambda x:0 if x < 11 else x)
merge_table['AGE'] = merge_table['AGE'].map(lambda x:10 if x >10 and x<21 else x)
merge_table['AGE'] = merge_table['AGE'].map(lambda x:20 if x >20 and x<31 else x)
merge_table['AGE'] = merge_table['AGE'].map(lambda x:30 if x >30 and x<41 else x)
merge_table['AGE'] = merge_table['AGE'].map(lambda x:40 if x >40 and x<51 else x)
merge_table['AGE'] = merge_table['AGE'].map(lambda x:50 if x >50 and x<61 else x)
merge_table['AGE'] = merge_table['AGE'].map(lambda x:60 if x >60 and x<71 else x)
merge_table['AGE'] = merge_table['AGE'].map(lambda x:70 if x >70 and x<81 else x)
merge_table['AGE'] = merge_table['AGE'].map(lambda x:80 if x >80  else x)


merge_table['AGE'] = merge_table['AGE'].map(lambda x:100 if x == 50 else x) 
merge_table['AGE'] = merge_table['AGE'].map(lambda x:70 if x == 30 or x == 40 or x == 60else x) 
merge_table['AGE'] = merge_table['AGE'].map(lambda x:40 if x == 20 else x) 
merge_table['AGE'] = merge_table['AGE'].map(lambda x:0 if  x != 100 and x!=70 and x!=40  else x)

In [82]:
merge_table['MAXCRDT']= merge_table['MAXCRDT'].map(lambda x:80 if x<=6 else x)
merge_table['MAXCRDT']= merge_table['MAXCRDT'].map(lambda x:50 if x<50 and x>7 else x)
merge_table['MAXCRDT'] = merge_table['MAXCRDT'].map(lambda x:0 if x!= 80 and x!=50  else x)

In [83]:
merge_table['CTPR'] = merge_table['CTPR'].map(lambda x:50 if x == '강원' or x == '광주' or x == '부산' or x == '인천' or x == '전북' else x) 
merge_table['CTPR'] = merge_table['CTPR'].map(lambda x:30 if x == '경기' or x=='경남' or x=='경북'  or x=='대구'or x=='대전' or x=='서울' or x=='전남' else x)
merge_table['CTPR'] = merge_table['CTPR'].map(lambda x:0 if  x != 30 and x!=50  else x)

In [84]:
merge_table["ACCI_OCCP_GRP1"] = merge_table["ACCI_OCCP_GRP1"].map(lambda x : 4 if x == '2.자영업' else x)   
merge_table["ACCI_OCCP_GRP1"] = merge_table["ACCI_OCCP_GRP1"].map(lambda x : 3 if x == '1.주부' or x == '5.서비스' else x)    
merge_table["ACCI_OCCP_GRP1"] = merge_table["ACCI_OCCP_GRP1"].map(lambda x : 2 if x == '3.사무직' or x == '8.기타' else x)   
merge_table["ACCI_OCCP_GRP1"] = merge_table["ACCI_OCCP_GRP1"].map(lambda x : 1 if x == '4.전문직' or x == '6.제조업' or x == '7.1차산업' else x)    
merge_table["ACCI_OCCP_GRP1"].fillna((merge_table["ACCI_OCCP_GRP1"].mean()), inplace=True)

In [85]:
merge_table["CRNT_PROG_DVSN"] = merge_table["CRNT_PROG_DVSN"].map(lambda x : 10 if x == 33 else x)   
merge_table["CRNT_PROG_DVSN"] = merge_table["CRNT_PROG_DVSN"].map(lambda x : 6 if x == 23 else x)   
merge_table["CRNT_PROG_DVSN"] = merge_table["CRNT_PROG_DVSN"].map(lambda x : 3 if x == 11 else x)   
merge_table["CRNT_PROG_DVSN"] = merge_table["CRNT_PROG_DVSN"].map(lambda x : 1 if x != 10 and x != 6 and x != 3 else x)   
merge_table["CRNT_PROG_DVSN"].fillna((merge_table["CRNT_PROG_DVSN"].mean()), inplace=True)

In [86]:
merge_table["DMND_RESN_CODE"] = merge_table["DMND_RESN_CODE"].map(lambda x : 100 if x == 2 or x == 4 else x)   
merge_table["DMND_RESN_CODE"] = merge_table["DMND_RESN_CODE"].map(lambda x : 40 if x == 5 else x)   
merge_table["DMND_RESN_CODE"] = merge_table["DMND_RESN_CODE"].map(lambda x : 10 if x == 1 or x == 3 or x == 6 else x)   
merge_table["DMND_RESN_CODE"] = merge_table["DMND_RESN_CODE"].map(lambda x : 5 if x == 7 else x)   
merge_table["DMND_RESN_CODE"] = merge_table["DMND_RESN_CODE"].map(lambda x : 1 if x == 9 else x)   
merge_table["DMND_RESN_CODE"].fillna((merge_table["DMND_RESN_CODE"].mean()), inplace=True)

In [87]:
merge_table['SALE_CHNL_CODE']=merge_table['SALE_CHNL_CODE'].map(lambda x: 70 if  x == 1 else x)
merge_table['SALE_CHNL_CODE']=merge_table['SALE_CHNL_CODE'].map(lambda x: 30 if  x == 2 else x)
merge_table['SALE_CHNL_CODE']=merge_table['SALE_CHNL_CODE'].map(lambda x: 130 if  x == 3 else x)
merge_table['SALE_CHNL_CODE']=merge_table['SALE_CHNL_CODE'].map(lambda x: 90 if  x == 4 else x)
merge_table['SALE_CHNL_CODE']=merge_table['SALE_CHNL_CODE'].map(lambda x: 10 if  x == 5 else x)
merge_table['SALE_CHNL_CODE']=merge_table['SALE_CHNL_CODE'].map(lambda x: 50 if  x == 6 else x)
merge_table['SALE_CHNL_CODE']=merge_table['SALE_CHNL_CODE'].map(lambda x: 110 if  x == 7 else x)

In [88]:
merge_table['CNTT_STAT_CODE']=merge_table['CNTT_STAT_CODE'].map(lambda x: 0 if x == 1 or x == 2 or x == 9 or x == 'A' or x == 'C' or x == 'H' or x == 'I' or x == 'L' else x)
merge_table['CNTT_STAT_CODE']=merge_table['CNTT_STAT_CODE'].map(lambda x: 2 if x == 3 or x == 'B' or x == 'E' or x == 'J' else 4)

In [89]:
merge_table.sort(columns="CUST_ID", axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')

/home/jangsion/miniconda3/envs/ml_python/lib/python3.5/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

,CUST_ID,SIU_CUST_YN,AGE,CTPR,MAXCRDT,ACCI_OCCP_GRP1,CRNT_PROG_DVSN,DMND_RESN_CODE,VLID_HOSP_OTDA,NON_PAY_RATIO,SALE_CHNL_CODE,CNTT_STAT_CODE
7665,37,None,70,30,0.0,3.00000,3,40,0,0.000000,70,2
13524,37,None,70,30,0.0,3.00000,3,40,0,0.000000,70,2
9147,37,None,70,30,0.0,3.00000,3,40,0,0.000000,70,4
7666,37,None,70,30,0.0,3.00000,3,40,0,0.000000,70,2
7669,37,None,70,30,0.0,3.00000,3,40,0,0.000000,70,2
9146,37,None,70,30,0.0,3.00000,3,40,0,0.000000,70,4
24157,37,None,70,30,0.0,3.00000,3,40,0,0.000000,70,4
7668,37,None,70,30,0.0,3.00000,3,40,0,0.000000,70,2
7667,37,None,70,30,0.0,3.00000,3,40,0,0.000000,70,2
14153,51,None,70,30,0.0,4.00000,6,10,8,0.000000,70,4
16991,51,None,70,30,0.0,3.00000,6,100,8,0.000000,30,4
21399,51,None,70,30,0.0,4.00000,3,100,6,0.000000,70,4
13232,51,None,70,30,0.0,3.00000,6,40,0,0.000000,30,4
16085,51,None,70,30,0.0,4.00000,6,100,6,0.000000,30,4
3583,51,None,70,30,0.0,3.00000,6,40,0,0.000000,70,4
24715,51,None,70,30,0.0,4.00000,6,10,0,0.000000,30,4
17110,51,None,70,30,0.0,4.00000,6,100,8,0.000000,70,4
6103,51,None,70,30,0.0,3.00000,6,40,0,0.000000,70,2
7206,51,None,70,30,0.0,2.43492,6,100,8,0.880125,70,2
1685,51,None,70,30,0.0,3.00000,6,100,8,0.000000,30,4
7117,51,None,70,30,0.0,4.00000,6,100,6,0.000000,70,4
7114,51,None,70,30,0.0,3.00000,6,100,8,0.000000,70,4
14476,51,None,70,30,0.0,4.00000,3,100,6,0.000000,30,4
16728,51,None,70,30,0.0,4.00000,6,10,8,0.000000,30,4
19707,51,None,70,30,0.0,4.00000,3,100,6,0.000000,70,2
17184,51,None,70,30,0.0,3.00000,6,10,0,0.000000,30,2
17138,51,None,70,30,0.0,3.00000,6,100,8,0.000000,70,4
11923,51,None,70,30,0.0,4.00000,6,100,6,0.000000,30,2
2987,51,None,70,30,0.0,4.00000,6,100,8,0.000000,70,4
22432,51,None,70,30,0.0,4.00000,6,10,0,0.000000,30,2
...,...,...,...,...,...,...,...,...,...,...,...,...
21117,22294,None,70,0,80.0,1.00000,6,10,3,0.000000,70,4
13138,22294,None,70,0,80.0,1.00000,6,10,5,0.000000,70,4
15617,22294,None,70,0,80.0,1.00000,6,10,0,0.000000,70,4
24103,22294,None,70,0,80.0,1.00000,6,10,1,0.463870,70,4
26437,22294,None,70,0,80.0,1.00000,6,10,5,0.028090,70,4
1214,22294,None,70,0,80.0,1.00000,6,10,5,0.555556,70,4
22798,22295,None,100,30,80.0,3.00000,6,10,2,0.015699,70,4
16714,22295,None,100,30,80.0,3.00000,6,10,2,0.015699,70,4
17208,22295,None,100,30,80.0,3.00000,6,10,2,0.015699,70,2
26097,22295,None,100,30,80.0,3.00000,6,10,2,0.015699,70,2
12393,22304,None,70,30,50.0,2.00000,6,100,21,0.062777,70,2
7953,22305,None,70,30,80.0,3.00000,6,10,0,0.000000,70,4
2205,22305,None,70,30,80.0,3.00000,6,10,25,0.000000,70,4
14054,22305,None,70,30,80.0,3.00000,6,10,25,0.733057,70,4
4819,22320,None,70,30,50.0,2.00000,6,10,1,0.389291,70,4
11317,22328,None,70,30,80.0,1.00000,6,10,13,0.000000,50,4
6912,22328,None,70,30,80.0,1.00000,3,10,12,0.000000,50,4
11173,22329,None,0,30,80.0,2.00000,6,10,1,0.000000,70,4
14439,22329,None,0,30,80.0,2.00000,6,10,1,0.825186,70,4
2197,22342,None,40,50,80.0,1.00000,6,10,1,0.883392,30,4
59,22342,None,40,50,80.0,1.00000,6,10,1,0.883392,30,4
17483,22342,None,40,50,80.0,1.00000,6,10,3,0.663418,70,4
14580,22342,None,40,50,80.0,1.00000,6,10,3,0.663418,30,4
24439,22342,None,40,50,80.0,1.00000,6,10,3,0.663418,30,4
13233,22342,None,40,50,80.0,1.00000,6,10,1,0.883392,70,4
7753,22383,None,70,30,80.0,2.00000,10,10,1,0.000000,70,4
5889,22383,None,70,30,80.0,2.00000,10,10,1,0.726697,70,4
11609,22383,None,70,30,80.0,2.00000,10,10,0,0.000000,70,4
19574,22383,None,70,30,80.0,2.00000,6,10,0,0.000000,70,4
18732,22383,None,70,30,80.0,2.00000,6,10,1,0.000000,70,4

In [90]:
version_3 = set([ tuple(line) for line in merge_table.values.tolist()])

In [91]:
real_data = []
with open("merge_table_test", "r") as sion:  
    datas = sion.readlines()
    for data in datas:
        data = data.split(",")
        real_data.append(data)

In [92]:
columns = []
for i in merge_table.columns:
    columns.append(i)

In [93]:
result = [] 
result.append(columns)

In [94]:
for i in version_3:
    result.append(list(i))

In [95]:
for i in range(len(result)):
    for j in range(len(result[i])):
        result[i][j] = str(result[i][j])

In [96]:
result_2 = []
for i in result:
    i[-1] = i[-1]+"\n"
    result_2.append(i)

In [97]:
with open("merge_table_test_real", "w") as sion: 
    for data in result_2:
        data = ",".join(data)
        sion.write(data)
    sion.close()